[package]
name = "spoofylightslib"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["lib"]
bench = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"